stages:
  data_ingestion:
    cmd: python src/Titanic_dataset_analysis/pipeline/stage_01_data_ingestion.py
    deps:
      - src/Titanic_dataset_analysis/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion


  data_preprocessing:
    cmd: python src/Titanic_dataset_analysis/pipeline/stage_02_data_preprocessing.py
    deps:
      - src/Titanic_dataset_analysis/pipeline/stage_02_data_preprocessing.py
      - config/config.yaml
      - artifacts/data_ingestion/train.csv
    outs:
      - artifacts/data_preprocessing/titanic_preprocessed.csv



  model_training:
    cmd: python src/Titanic_dataset_analysis/pipeline/stage_03_model_training.py
    deps:
      - src/Titanic_dataset_analysis/pipeline/stage_03_model_training.py
      - config/config.yaml
      - artifacts/data_preprocessing/titanic_preprocessed.csv
    params:
      - splitratio
      - seed
      - regParam
      - elasticNetParam
      - number_of_folds
      - sparkSessionTitle
    outs:
      - artifacts/model_training/best_model
      - artifacts/model_training/test_data


  

  mlflow_model_management:
    cmd: python src/Titanic_dataset_analysis/pipeline/stage_04_mlflow_model_management.py
    deps:
      - src/Titanic_dataset_analysis/pipeline/stage_04_mlflow_model_management.py
      - config/config.yaml
      - artifacts/model_training/best_model
    params:
      - experiment_name
      - mlflow_uri
      - mlflow_run_name
      - sparkSessionTitle
    metrics:
    - model_info.json:
        cache: false